"""Initial migration

Revision ID: 7cc3d9ed8b94
Revises: 
Create Date: 2025-05-11 00:15:03.114332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc3d9ed8b94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('id_author', sa.Integer(), nullable=True),
    sa.Column('id_category', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_author'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['id_category'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_loan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_book', sa.Integer(), nullable=False),
    sa.Column('id_loan', sa.Integer(), nullable=False),
    sa.Column('book_quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_book'], ['books.id'], ),
    sa.ForeignKeyConstraint(['id_loan'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_loan')
    op.drop_table('loans')
    op.drop_table('books')
    op.drop_table('clients')
    op.drop_table('categories')
    op.drop_table('authors')
    # ### end Alembic commands ###
