"""add phone to client

Revision ID: ee9d5d295b3c
Revises: 7cc3d9ed8b94
Create Date: 2025-05-15 16:00:00.756196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee9d5d295b3c'
down_revision = '7cc3d9ed8b94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'phone')
    # ### end Alembic commands ###
